// Generated by CoffeeScript 1.10.0
var exec, loopFunc;

exec = require('child_process').exec;

loopFunc = exec('nfc-list', function(err, stdout, stderr) {
  console.log(stdout: ${stdout});
  console.log(stderr: ${stderr});
  if (error !== null) {
    return console.log(exec error: ${error});
  }
});

setTimeout(function() {
  return loopFunc();
}, 3000);
